name: wasteagram
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  location: ^3.0.2
  image_picker: ^0.6.7+4
  path: ^1.6.4
  intl: ^0.16.1
  cached_network_image: ^2.2.0+1
  firebase_analytics: ^5.0.16
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  sentry: ^3.0.1
  flutter_driver:
    sdk: flutter


flutter:

  uses-material-design: true
